/// Тематический план «Для начинающих»: четыре квартала, 71 день.
/// Каждый день содержит одну главу и краткую мысль для фокуса чтения.
import 'package:bible_app/journal/thematic_reading_plan_models.dart';

const String kBeginnerPlanPickerButtonLabel = 'Для начинающих';

const int kBeginnerPlanDayCount = 71;

const List<int> kBeginnerQuarterDayCounts = [21, 28, 16, 6];

const List<String> kBeginnerQuarterThemes = [
  'Личность Иисуса',
  'История и сила Церкви',
  'Богословие спасения',
  'Свобода во Христе',
];

const List<ThematicReadingDay> kBeginnerReadingPlanDays = [
  ThematicReadingDay(theme: 'Слово, Бог', rows: [ThematicReadingRow(refDisplay: 'Иоанна 1', book: 'Иоанна', chapter: 1, startVerse: 1, idea: 'Пролог Евангелия открывает Иисуса как вечное Слово и истинного Бога.')]),
  ThematicReadingDay(theme: 'Чудо в Кане', rows: [ThematicReadingRow(refDisplay: 'Иоанна 2', book: 'Иоанна', chapter: 2, startVerse: 1, idea: 'Первое чудо Иисуса в Кане раскрывает Его славу и учит доверию Ему.')]),
  ThematicReadingDay(theme: 'Никодим, рождение свыше', rows: [ThematicReadingRow(refDisplay: 'Иоанна 3', book: 'Иоанна', chapter: 3, startVerse: 1, idea: 'Разговор с Никодимом объясняет необходимость рождения свыше и веры в Сына.')]),
  ThematicReadingDay(theme: 'Самарянка', rows: [ThematicReadingRow(refDisplay: 'Иоанна 4', book: 'Иоанна', chapter: 4, startVerse: 1, idea: 'Встреча у колодца показывает, что Иисус дает живую воду каждому, кто жаждет.')]),
  ThematicReadingDay(theme: 'Исцеление в субботу', rows: [ThematicReadingRow(refDisplay: 'Иоанна 5', book: 'Иоанна', chapter: 5, startVerse: 1, idea: 'Исцеление расслабленного и спор о субботе подчеркивают власть Иисуса как Сына Божьего.')]),
  ThematicReadingDay(theme: 'Хлеб жизни', rows: [ThematicReadingRow(refDisplay: 'Иоанна 6', book: 'Иоанна', chapter: 6, startVerse: 1, idea: 'После насыщения множества Иисус открывает Себя как хлеб жизни для мира.')]),
  ThematicReadingDay(theme: 'Праздник Кущей', rows: [ThematicReadingRow(refDisplay: 'Иоанна 7', book: 'Иоанна', chapter: 7, startVerse: 1, idea: 'Во время праздника Иисус зовет жаждущих прийти к Нему и обещает потоки живой воды.')]),
  ThematicReadingDay(theme: 'Свет миру, истина', rows: [ThematicReadingRow(refDisplay: 'Иоанна 8', book: 'Иоанна', chapter: 8, startVerse: 1, idea: 'Иисус называет Себя Светом миру и освобождает истиной тех, кто пребывает в Его слове.')]),
  ThematicReadingDay(theme: 'Исцеление слепорожденного', rows: [ThematicReadingRow(refDisplay: 'Иоанна 9', book: 'Иоанна', chapter: 9, startVerse: 1, idea: 'Исцеление слепорожденного показывает духовную слепоту и истинную веру.')]),
  ThematicReadingDay(theme: 'Добрый Пастырь', rows: [ThematicReadingRow(refDisplay: 'Иоанна 10', book: 'Иоанна', chapter: 10, startVerse: 1, idea: 'Иисус как Добрый Пастырь знает Своих овец и отдает за них жизнь.')]),
  ThematicReadingDay(theme: 'Воскрешение Лазаря', rows: [ThematicReadingRow(refDisplay: 'Иоанна 11', book: 'Иоанна', chapter: 11, startVerse: 1, idea: 'Перед лицом смерти Иисус открывает Себя как воскресение и жизнь.')]),
  ThematicReadingDay(theme: 'Вход в Иерусалим', rows: [ThematicReadingRow(refDisplay: 'Иоанна 12', book: 'Иоанна', chapter: 12, startVerse: 1, idea: 'Торжественный вход и слова Иисуса готовят учеников к Его крестному пути.')]),
  ThematicReadingDay(theme: 'Омовение ног', rows: [ThematicReadingRow(refDisplay: 'Иоанна 13', book: 'Иоанна', chapter: 13, startVerse: 1, idea: 'Омовение ног учит смиренному служению и любви как отличительному знаку учеников.')]),
  ThematicReadingDay(theme: 'Путь, Истина и Жизнь', rows: [ThematicReadingRow(refDisplay: 'Иоанна 14', book: 'Иоанна', chapter: 14, startVerse: 1, idea: 'Иисус утешает учеников и утверждает, что путь к Отцу только через Него.')]),
  ThematicReadingDay(theme: 'Лоза и ветви', rows: [ThematicReadingRow(refDisplay: 'Иоанна 15', book: 'Иоанна', chapter: 15, startVerse: 1, idea: 'Пребывание во Христе как в истинной лозе приносит плод и радость послушания.')]),
  ThematicReadingDay(theme: 'Обещание Духа Святого', rows: [ThematicReadingRow(refDisplay: 'Иоанна 16', book: 'Иоанна', chapter: 16, startVerse: 1, idea: 'Иисус обещает Утешителя, Который наставит учеников на всякую истину.')]),
  ThematicReadingDay(theme: 'Первосвященническая молитва', rows: [ThematicReadingRow(refDisplay: 'Иоанна 17', book: 'Иоанна', chapter: 17, startVerse: 1, idea: 'В молитве Иисуса звучат темы славы, единства учеников и их освящения истиной.')]),
  ThematicReadingDay(theme: 'Арест Иисуса', rows: [ThematicReadingRow(refDisplay: 'Иоанна 18', book: 'Иоанна', chapter: 18, startVerse: 1, idea: 'Арест и допрос Иисуса раскрывают Его добровольное принятие страданий.')]),
  ThematicReadingDay(theme: 'Распятие', rows: [ThematicReadingRow(refDisplay: 'Иоанна 19', book: 'Иоанна', chapter: 19, startVerse: 1, idea: 'На кресте Христос завершает дело искупления и исполняет Писание.')]),
  ThematicReadingDay(theme: 'Воскресение', rows: [ThematicReadingRow(refDisplay: 'Иоанна 20', book: 'Иоанна', chapter: 20, startVerse: 1, idea: 'Пустая гробница и явления воскресшего Христа утверждают учеников в вере.')]),
  ThematicReadingDay(theme: 'Явление ученикам', rows: [ThematicReadingRow(refDisplay: 'Иоанна 21', book: 'Иоанна', chapter: 21, startVerse: 1, idea: 'Восстановление Петра и поручение пасти овец завершают Евангелие надеждой.')]),
  ThematicReadingDay(theme: 'Вознесение Иисуса и обещание силы Святого Духа.', rows: [ThematicReadingRow(refDisplay: 'Деяния 1', book: 'Деяния', chapter: 1, startVerse: 1, idea: 'Вознесение Иисуса и обещание силы Святого Духа.')]),
  ThematicReadingDay(theme: 'Пятидесятница: сошествие Духа и рождение первой церкви.', rows: [ThematicReadingRow(refDisplay: 'Деяния 2', book: 'Деяния', chapter: 2, startVerse: 1, idea: 'Пятидесятница: сошествие Духа и рождение первой церкви.')]),
  ThematicReadingDay(theme: 'Исцеление хромого и проповедь Петра о покаянии.', rows: [ThematicReadingRow(refDisplay: 'Деяния 3', book: 'Деяния', chapter: 3, startVerse: 1, idea: 'Исцеление хромого и проповедь Петра о покаянии.')]),
  ThematicReadingDay(theme: 'Смелость учеников перед судом и единство верующих.', rows: [ThematicReadingRow(refDisplay: 'Деяния 4', book: 'Деяния', chapter: 4, startVerse: 1, idea: 'Смелость учеников перед судом и единство верующих.')]),
  ThematicReadingDay(theme: 'Важность искренности перед Богом и чудеса апостолов.', rows: [ThematicReadingRow(refDisplay: 'Деяния 5', book: 'Деяния', chapter: 5, startVerse: 1, idea: 'Важность искренности перед Богом и чудеса апостолов.')]),
  ThematicReadingDay(theme: 'Избрание первых служителей (диаконов) для помощи нуждающимся.', rows: [ThematicReadingRow(refDisplay: 'Деяния 6', book: 'Деяния', chapter: 6, startVerse: 1, idea: 'Избрание первых служителей (диаконов) для помощи нуждающимся.')]),
  ThematicReadingDay(theme: 'Речь Стефана об истории Израиля и его мученическая смерть.', rows: [ThematicReadingRow(refDisplay: 'Деяния 7', book: 'Деяния', chapter: 7, startVerse: 1, idea: 'Речь Стефана об истории Израиля и его мученическая смерть.')]),
  ThematicReadingDay(theme: 'Распространение веры за пределы Иерусалима (Филипп и эфиоп).', rows: [ThematicReadingRow(refDisplay: 'Деяния 8', book: 'Деяния', chapter: 8, startVerse: 1, idea: 'Распространение веры за пределы Иерусалима (Филипп и эфиоп).')]),
  ThematicReadingDay(theme: 'Чудесное обращение Савла (будущего апостола Павла).', rows: [ThematicReadingRow(refDisplay: 'Деяния 9', book: 'Деяния', chapter: 9, startVerse: 1, idea: 'Чудесное обращение Савла (будущего апостола Павла).')]),
  ThematicReadingDay(theme: 'Евангелие открывается для язычников (Петр и Корнилий).', rows: [ThematicReadingRow(refDisplay: 'Деяния 10', book: 'Деяния', chapter: 10, startVerse: 1, idea: 'Евангелие открывается для язычников (Петр и Корнилий).')]),
  ThematicReadingDay(theme: 'Церковь в Антиохии: верующих впервые называют «христианами».', rows: [ThematicReadingRow(refDisplay: 'Деяния 11', book: 'Деяния', chapter: 11, startVerse: 1, idea: 'Церковь в Антиохии: верующих впервые называют «христианами».')]),
  ThematicReadingDay(theme: 'Чудесное освобождение Петра из тюрьмы.', rows: [ThematicReadingRow(refDisplay: 'Деяния 12', book: 'Деяния', chapter: 12, startVerse: 1, idea: 'Чудесное освобождение Петра из тюрьмы.')]),
  ThematicReadingDay(theme: 'Начало первого миссионерского путешествия Павла.', rows: [ThematicReadingRow(refDisplay: 'Деяния 13', book: 'Деяния', chapter: 13, startVerse: 1, idea: 'Начало первого миссионерского путешествия Павла.')]),
  ThematicReadingDay(theme: 'Испытания и стойкость Павла в проповеди.', rows: [ThematicReadingRow(refDisplay: 'Деяния 14', book: 'Деяния', chapter: 14, startVerse: 1, idea: 'Испытания и стойкость Павла в проповеди.')]),
  ThematicReadingDay(theme: 'Апостольский собор: спасение дается благодатью, а не обрядами.', rows: [ThematicReadingRow(refDisplay: 'Деяния 15', book: 'Деяния', chapter: 15, startVerse: 1, idea: 'Апостольский собор: спасение дается благодатью, а не обрядами.')]),
  ThematicReadingDay(theme: 'Филиппы: темничный страж находит веру.', rows: [ThematicReadingRow(refDisplay: 'Деяния 16', book: 'Деяния', chapter: 16, startVerse: 1, idea: 'Филиппы: темничный страж находит веру.')]),
  ThematicReadingDay(theme: 'Проповедь в Афинах: Бог — Творец всех людей.', rows: [ThematicReadingRow(refDisplay: 'Деяния 17', book: 'Деяния', chapter: 17, startVerse: 1, idea: 'Проповедь в Афинах: Бог — Творец всех людей.')]),
  ThematicReadingDay(theme: 'Служение в Коринфе и укрепление новых церквей.', rows: [ThematicReadingRow(refDisplay: 'Деяния 18', book: 'Деяния', chapter: 18, startVerse: 1, idea: 'Служение в Коринфе и укрепление новых церквей.')]),
  ThematicReadingDay(theme: 'Проповедь в Эфесе и победа над суевериями.', rows: [ThematicReadingRow(refDisplay: 'Деяния 19', book: 'Деяния', chapter: 19, startVerse: 1, idea: 'Проповедь в Эфесе и победа над суевериями.')]),
  ThematicReadingDay(theme: 'Прощание Павла с пресвитерами: «блаженнее давать, нежели принимать».', rows: [ThematicReadingRow(refDisplay: 'Деяния 20', book: 'Деяния', chapter: 20, startVerse: 1, idea: 'Прощание Павла с пресвитерами: «блаженнее давать, нежели принимать».')]),
  ThematicReadingDay(theme: 'Арест Павла в Иерусалиме ради Евангелия.', rows: [ThematicReadingRow(refDisplay: 'Деяния 21', book: 'Деяния', chapter: 21, startVerse: 1, idea: 'Арест Павла в Иерусалиме ради Евангелия.')]),
  ThematicReadingDay(theme: 'Защитная речь Павла и рассказ о его призвании.', rows: [ThematicReadingRow(refDisplay: 'Деяния 22', book: 'Деяния', chapter: 22, startVerse: 1, idea: 'Защитная речь Павла и рассказ о его призвании.')]),
  ThematicReadingDay(theme: 'Заговор против Павла и его переправка в Кесарию.', rows: [ThematicReadingRow(refDisplay: 'Деяния 23', book: 'Деяния', chapter: 23, startVerse: 1, idea: 'Заговор против Павла и его переправка в Кесарию.')]),
  ThematicReadingDay(theme: 'Суд перед правителем Феликсом.', rows: [ThematicReadingRow(refDisplay: 'Деяния 24', book: 'Деяния', chapter: 24, startVerse: 1, idea: 'Суд перед правителем Феликсом.')]),
  ThematicReadingDay(theme: 'Павел взывает к суду кесаря (императора).', rows: [ThematicReadingRow(refDisplay: 'Деяния 25', book: 'Деяния', chapter: 25, startVerse: 1, idea: 'Павел взывает к суду кесаря (императора).')]),
  ThematicReadingDay(theme: 'Свидетельство Павла перед царем Агриппой.', rows: [ThematicReadingRow(refDisplay: 'Деяния 26', book: 'Деяния', chapter: 26, startVerse: 1, idea: 'Свидетельство Павла перед царем Агриппой.')]),
  ThematicReadingDay(theme: 'Кораблекрушение на пути в Рим и Божья защита.', rows: [ThematicReadingRow(refDisplay: 'Деяния 27', book: 'Деяния', chapter: 27, startVerse: 1, idea: 'Кораблекрушение на пути в Рим и Божья защита.')]),
  ThematicReadingDay(theme: 'Прибытие в Рим и проповедь без преград.', rows: [ThematicReadingRow(refDisplay: 'Деяния 28', book: 'Деяния', chapter: 28, startVerse: 1, idea: 'Прибытие в Рим и проповедь без преград.')]),
  ThematicReadingDay(theme: 'Гнев Божий на грех и сила Евангелия для спасения.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 1', book: 'Римлянам', chapter: 1, startVerse: 1, idea: 'Гнев Божий на грех и сила Евангелия для спасения.')]),
  ThematicReadingDay(theme: 'Божий суд справедлив ко всем, независимо от знания закона.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 2', book: 'Римлянам', chapter: 2, startVerse: 1, idea: 'Божий суд справедлив ко всем, независимо от знания закона.')]),
  ThematicReadingDay(theme: 'Все согрешили, но оправданы даром по вере в Иисуса.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 3', book: 'Римлянам', chapter: 3, startVerse: 1, idea: 'Все согрешили, но оправданы даром по вере в Иисуса.')]),
  ThematicReadingDay(theme: 'Пример Авраама: вера вменяется в праведность.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 4', book: 'Римлянам', chapter: 4, startVerse: 1, idea: 'Пример Авраама: вера вменяется в праведность.')]),
  ThematicReadingDay(theme: 'Мир с Богом через Христа и торжество благодати.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 5', book: 'Римлянам', chapter: 5, startVerse: 1, idea: 'Мир с Богом через Христа и торжество благодати.')]),
  ThematicReadingDay(theme: 'Мы умерли для греха, чтобы жить для Бога.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 6', book: 'Римлянам', chapter: 6, startVerse: 1, idea: 'Мы умерли для греха, чтобы жить для Бога.')]),
  ThematicReadingDay(theme: 'Внутренняя борьба человека с греховной природой.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 7', book: 'Римлянам', chapter: 7, startVerse: 1, idea: 'Внутренняя борьба человека с греховной природой.')]),
  ThematicReadingDay(theme: 'Жизнь в Духе: ничто не может отлучить нас от любви Божией.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 8', book: 'Римлянам', chapter: 8, startVerse: 1, idea: 'Жизнь в Духе: ничто не может отлучить нас от любви Божией.')]),
  ThematicReadingDay(theme: 'Божье избрание и Его суверенитет.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 9', book: 'Римлянам', chapter: 9, startVerse: 1, idea: 'Божье избрание и Его суверенитет.')]),
  ThematicReadingDay(theme: 'Вера приходит от слышания Слова Божьего.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 10', book: 'Римлянам', chapter: 10, startVerse: 1, idea: 'Вера приходит от слышания Слова Божьего.')]),
  ThematicReadingDay(theme: 'Божий план для Израиля и милость ко всем народам.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 11', book: 'Римлянам', chapter: 11, startVerse: 1, idea: 'Божий план для Израиля и милость ко всем народам.')]),
  ThematicReadingDay(theme: 'Жизнь как «жертва живая»: практические советы по любви.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 12', book: 'Римлянам', chapter: 12, startVerse: 1, idea: 'Жизнь как «жертва живая»: практические советы по любви.')]),
  ThematicReadingDay(theme: 'Отношение к властям и исполнение закона через любовь.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 13', book: 'Римлянам', chapter: 13, startVerse: 1, idea: 'Отношение к властям и исполнение закона через любовь.')]),
  ThematicReadingDay(theme: 'Принятие немощных в вере и отказ от осуждения.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 14', book: 'Римлянам', chapter: 14, startVerse: 1, idea: 'Принятие немощных в вере и отказ от осуждения.')]),
  ThematicReadingDay(theme: 'Христос — пример служения другим и надежда для всех.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 15', book: 'Римлянам', chapter: 15, startVerse: 1, idea: 'Христос — пример служения другим и надежда для всех.')]),
  ThematicReadingDay(theme: 'Личные приветствия Павла и предостережение от разделений.', rows: [ThematicReadingRow(refDisplay: 'Римлянам 16', book: 'Римлянам', chapter: 16, startVerse: 1, idea: 'Личные приветствия Павла и предостережение от разделений.')]),
  ThematicReadingDay(theme: 'Евангелие от Павла', rows: [ThematicReadingRow(refDisplay: 'Галатам 1', book: 'Галатам', chapter: 1, startVerse: 1, idea: 'Павел отстаивает божественное происхождение Евангелия и верность Христу.')]),
  ThematicReadingDay(theme: 'Оправдание верой', rows: [ThematicReadingRow(refDisplay: 'Галатам 2', book: 'Галатам', chapter: 2, startVerse: 1, idea: 'Человек оправдывается не делами закона, а верой в Иисуса Христа.')]),
  ThematicReadingDay(theme: 'Вера и закон', rows: [ThematicReadingRow(refDisplay: 'Галатам 3', book: 'Галатам', chapter: 3, startVerse: 1, idea: 'Обетование Аврааму исполняется по вере, а не через дела закона.')]),
  ThematicReadingDay(theme: 'Сыны Божии', rows: [ThematicReadingRow(refDisplay: 'Галатам 4', book: 'Галатам', chapter: 4, startVerse: 1, idea: 'Во Христе верующие получают усыновление и свободу от рабства закона.')]),
  ThematicReadingDay(theme: 'Свобода и плод Духа', rows: [ThematicReadingRow(refDisplay: 'Галатам 5', book: 'Галатам', chapter: 5, startVerse: 1, idea: 'Христианская свобода выражается в любви и плоде Святого Духа.')]),
  ThematicReadingDay(theme: 'Жизнь в духе', rows: [ThematicReadingRow(refDisplay: 'Галатам 6', book: 'Галатам', chapter: 6, startVerse: 1, idea: 'Практическая жизнь в духе ведет к взаимной поддержке и верности Христу.')]),
];
